//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryMatriculaEscritorio.webserviceMatricula {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Matricula", Namespace="http://schemas.datacontract.org/2004/07/WFCServiceMatricula")]
    [System.SerializableAttribute()]
    public partial class Matricula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apoderadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_matriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string seccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string turnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apoderado {
            get {
                return this.apoderadoField;
            }
            set {
                if ((object.ReferenceEquals(this.apoderadoField, value) != true)) {
                    this.apoderadoField = value;
                    this.RaisePropertyChanged("apoderado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                if ((object.ReferenceEquals(this.dniField, value) != true)) {
                    this.dniField = value;
                    this.RaisePropertyChanged("dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grado {
            get {
                return this.gradoField;
            }
            set {
                if ((object.ReferenceEquals(this.gradoField, value) != true)) {
                    this.gradoField = value;
                    this.RaisePropertyChanged("grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_matricula {
            get {
                return this.id_matriculaField;
            }
            set {
                if ((this.id_matriculaField.Equals(value) != true)) {
                    this.id_matriculaField = value;
                    this.RaisePropertyChanged("id_matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nivel {
            get {
                return this.nivelField;
            }
            set {
                if ((object.ReferenceEquals(this.nivelField, value) != true)) {
                    this.nivelField = value;
                    this.RaisePropertyChanged("nivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string seccion {
            get {
                return this.seccionField;
            }
            set {
                if ((object.ReferenceEquals(this.seccionField, value) != true)) {
                    this.seccionField = value;
                    this.RaisePropertyChanged("seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string turno {
            get {
                return this.turnoField;
            }
            set {
                if ((object.ReferenceEquals(this.turnoField, value) != true)) {
                    this.turnoField = value;
                    this.RaisePropertyChanged("turno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webserviceMatricula.IServiceMatricula")]
    public interface IServiceMatricula {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/ListarMatriculas", ReplyAction="http://tempuri.org/IServiceMatricula/ListarMatriculasResponse")]
        System.Data.DataSet ListarMatriculas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/ListarMatriculas", ReplyAction="http://tempuri.org/IServiceMatricula/ListarMatriculasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarMatriculasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/BuscarporMatricula", ReplyAction="http://tempuri.org/IServiceMatricula/BuscarporMatriculaResponse")]
        System.Data.DataSet BuscarporMatricula(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/BuscarporMatricula", ReplyAction="http://tempuri.org/IServiceMatricula/BuscarporMatriculaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarporMatriculaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/RegistrarMatricula", ReplyAction="http://tempuri.org/IServiceMatricula/RegistrarMatriculaResponse")]
        string RegistrarMatricula(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/RegistrarMatricula", ReplyAction="http://tempuri.org/IServiceMatricula/RegistrarMatriculaResponse")]
        System.Threading.Tasks.Task<string> RegistrarMatriculaAsync(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/ActualizarMatricula", ReplyAction="http://tempuri.org/IServiceMatricula/ActualizarMatriculaResponse")]
        string ActualizarMatricula(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/ActualizarMatricula", ReplyAction="http://tempuri.org/IServiceMatricula/ActualizarMatriculaResponse")]
        System.Threading.Tasks.Task<string> ActualizarMatriculaAsync(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/EliminarMatricula", ReplyAction="http://tempuri.org/IServiceMatricula/EliminarMatriculaResponse")]
        string EliminarMatricula(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMatricula/EliminarMatricula", ReplyAction="http://tempuri.org/IServiceMatricula/EliminarMatriculaResponse")]
        System.Threading.Tasks.Task<string> EliminarMatriculaAsync(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMatriculaChannel : pryMatriculaEscritorio.webserviceMatricula.IServiceMatricula, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMatriculaClient : System.ServiceModel.ClientBase<pryMatriculaEscritorio.webserviceMatricula.IServiceMatricula>, pryMatriculaEscritorio.webserviceMatricula.IServiceMatricula {
        
        public ServiceMatriculaClient() {
        }
        
        public ServiceMatriculaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMatriculaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMatriculaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMatriculaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarMatriculas() {
            return base.Channel.ListarMatriculas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarMatriculasAsync() {
            return base.Channel.ListarMatriculasAsync();
        }
        
        public System.Data.DataSet BuscarporMatricula(int id) {
            return base.Channel.BuscarporMatricula(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarporMatriculaAsync(int id) {
            return base.Channel.BuscarporMatriculaAsync(id);
        }
        
        public string RegistrarMatricula(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula) {
            return base.Channel.RegistrarMatricula(obj_matricula);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarMatriculaAsync(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula) {
            return base.Channel.RegistrarMatriculaAsync(obj_matricula);
        }
        
        public string ActualizarMatricula(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula) {
            return base.Channel.ActualizarMatricula(obj_matricula);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarMatriculaAsync(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula) {
            return base.Channel.ActualizarMatriculaAsync(obj_matricula);
        }
        
        public string EliminarMatricula(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula) {
            return base.Channel.EliminarMatricula(obj_matricula);
        }
        
        public System.Threading.Tasks.Task<string> EliminarMatriculaAsync(pryMatriculaEscritorio.webserviceMatricula.Matricula obj_matricula) {
            return base.Channel.EliminarMatriculaAsync(obj_matricula);
        }
    }
}
